version: '3.8'

services:
  app:
    build: .
    container_name: moviebox_app
    command: bundle exec rails server -b 0.0.0.0
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      MONGODB_URI: mongodb://mongo:27017/moviebox

  mongo:
    image: mongo:6.0
    container_name: moviebox_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
